### ISSUE TITLE
SnowflakeOperatorAsync fails with % symbol

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astronomer-providers#958] opened 2023-04-12 15:18 UTC
**Describe the bug**
SnowflakeOperatorAsync is throwing a parsing error

**To Reproduce**
Use the SnowflakeOperatorAsync
Create a query using the `%b%` logic

will throw

```python
[2023-04-04T23:46:19.636+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/snowflake/operators/snowflake.py", line 109, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/snowflake/hooks/snowflake.py", line 71, in run
    cur.execute_async(sql_statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 813, in execute_async
    return self.execute(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 680, in execute
    query = command % processed_params
ValueError: unsupported format character 'b' (0x62) at index 10952
```

**Expected behavior**
Query is parsed successfully

**Desktop (please complete the following information):**
 - OS: MacOS, Debian
 - Browser Chrome

**Additional context**
User has stated that this does not happen with their current custom operator that builds off of the airflow snowflakeoperator

**Comment by rajaths010494** [comment] 2023-04-13 05:26
Can i get an example query?

**Comment by phanikumv** [comment] 2023-04-18 14:05
Fixed in https://github.com/astronomer/astronomer-providers/pull/962

**Comment by erdos2n** [comment] 2023-04-21 02:45
User still saw this error in their task logs 

```
[2023-04-21, 02:44:03 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 2082653 for task 01_TEST_PERCENTAGE_OPERATOR (unsupported format character 'b' (0x62) at index 34; 43)
```

here are the libraries 

```
astronomer-providers                     1.15.3
apache-airflow-providers-snowflake       4.0.3
snowflake-connector-python               2.9.0
snowflake-sqlalchemy                     1.4.4
```

**Comment by phanikumv** [comment] 2023-04-24 06:25
The issue is on snowflake-sqlalchemy side.

I have a another github issue for the same
https://github.com/snowflakedb/snowflake-sqlalchemy/issues/408

A workaround the customer can try while snowflake fixes the issue : replace the % sign with %%

**Comment by Lee-W** [comment] 2023-04-24 15:44
I'm not sure this is a bug. It looks more like how snowflake should be used to me. It's just how snowflake escape special character. I also find similar behavior on C# according to the [discussion](https://stackoverflow.com/questions/74044868/parametrized-query-using-like-with-snowflake-and-pass-the-values-from-snowflake). 

Python itself also have similar behavior

```
In [1]: print("%q" % 5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [1], line 1
----> 1 print("%q" % 5)

ValueError: unsupported format character 'q' (0x71) at index 1

In [2]: print("%%q %s" % 5)
%q 5
```

**Comment by phanikumv** [comment] 2023-04-24 17:24
A query containing the "%b%"  fails with `ValueError: unsupported format character 'b' (0x71) at index 1` , using the snowflake-sqlalchemy library while it doesnt fail on the snowflake UI, hence IMO its a bug

**Comment by Lee-W** [comment] 2023-04-25 00:39
I might be wrong and don't have the snowflake UI access to verify, but the description `A query containing the "%b%" fails` might lake a bit detail.

The following code works fine.

```python
sql = "SELECT CASE WHEN NAME ILIKE '%b%' THEN 'a' ELSE 'b' END AS test FROM PROVIDERS_FIVETRAN_DEV.S3.FIVETRAN_ANKIT_TEST;"

conn.execute_query(sql)
```

It fails when we provide parameter. Are we able to do similar thing on the snowflake UI to verify as well?

```python
sql = "SELECT CASE WHEN NAME ILIKE '%b%' THEN 'a' ELSE 'b' END AS test FROM PROVIDERS_FIVETRAN_DEV.S3.FIVETRAN_ANKIT_TEST;"

conn.execute_query(sql, {"test": "test"})
```

**Comment by vatsrahul1001** [comment] 2024-01-12 10:12
As we are deprecating providers, this might not be needed now. closing this

**Closed by vatsrahul1001** 2024-01-12 10:12 UTC
Labels: bug, pri/high
