### ISSUE TITLE
[SPIKE/RESEARCH] Async LambdaInvokeFunctionOperator

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#507] opened 2022-07-09 02:37 UTC
Acceptance Criteria:
Find a Python library that supports Asynchronous implementation for LambdaInvokeFunctionOperator if the official library does not support it. Document possible options and selection reasons for a particular library in this GitHub issue via a Summary comment.

Ensure that connection is set up and working.
Ensure overall feasibility for the async implementation the operator.

**Comment by pankajkoti** [comment] 2022-07-12 14:59
Explored the sync version of Operator, created a test Lambda function in our account, created a AWS policy to access this Lambda function and assigned to our integration-test user in AWS. Created an example DAG with the sync version and it runs fine. So, we're setup with the needed AWS configuration.

Will work next on figuring out how to implement the async version.

**Comment by pankajkoti** [comment] 2022-07-13 09:47
I am able to invoke a function using the asynchronous mode given by the library. It does invoke the function asynchronously & gives  a request ID in the response, however I don’t seem to find a utility given by AWS / boto3 to poll & fetch the status of this request ID. 

Following is the response we get after invoking the function asynchronously,
```
Lambda response metadata: {'RequestId': '1307e121-e051-4961-ad8d-e1b62cda3f93', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Wed, 13 Jul 2022 09:08:40 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '1307e121-e051-4961-ad8d-e1b62cda3f93', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-62ce8b98-692e899a2d0ca16679e4f984;sampled=0'}, 'RetryAttempts': 0}
[2022-07-13, 09:08:40 UTC] {aws_lambda.py:101} INFO - Lambda function invocation succeeded: {'RequestId': '1307e121-e051-4961-ad8d-e1b62cda3f93', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Wed, 13 Jul 2022 09:08:40 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '1307e121-e051-4961-ad8d-e1b62cda3f93', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-62ce8b98-692e899a2d0ca16679e4f984;sampled=0'}, 'RetryAttempts': 0}
```

**Comment by pankajkoti** [comment] 2022-07-13 09:49
Boto3 Lambda functions list: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.invoke

**Comment by phanikumv** [comment] 2022-07-13 09:51
Why cant we do it as mentioned in this link?
https://stackoverflow.com/questions/66505773/how-to-get-the-status-of-a-aws-lambda-function-with-boto3

**Comment by pankajkoti** [comment] 2022-07-13 10:01
@phanikumv The answer in the link is not to get the status of the function invocation but it instead is invoking the function in synchronous mode and waiting by itself for the completion of the function.

`InvocationType="RequestResponse"` means synchronous invocation, `InvocationType="Event"` means asynchronous invocation, but there does not seem to be a subsequent method to fetch the status of the asynchronous invocation.

**Comment by pankajkoti** [comment] 2022-07-13 10:05
As mentioned in the docs here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.invoke , the parameter values for `invocation_type` are described as:


**InvocationType** (string) --
Choose from the following options.

**RequestResponse** (default) - Invoke the function synchronously. Keep the connection open until the function returns a response or times out. The API response includes the function response and additional data.
**Event** - Invoke the function asynchronously. Send events that fail multiple times to the function's dead-letter queue (if it's configured). The API response only includes a status code.
**DryRun** - Validate parameter values and verify that the user or role has permission to invoke the function.

**Comment by pankajkoti** [comment] 2022-07-13 10:25
Like someone mentioned here: https://stackoverflow.com/questions/72165019/how-can-i-track-the-progress-status-of-an-asynchronous-aws-lambda-invocation , there seems to be no built-in way to track the status of async Lambda function invocation.

**Comment by pankajkoti** [comment] 2022-07-14 10:29
I asked on the Airflow OSS channel in the #airflow-aws channel. So far have got only reply mentioning the same that it may not be possible.

@phanikumv please check what should we do on this Spike.

**Comment by pankajkoti** [comment] 2022-07-15 04:27
Mark Richman, Senior Solutions Architect at AWS has confirmed that there is no way currently to get the invocation status. Hence, I believe it is not feasible to implement an async operator to await the status of a Lambda function invocation.

**Comment by pankajkoti** [comment] 2022-07-15 06:49
Closing the spike as the implementation is not feasible.

**Closed by pankajkoti** 2022-07-15 06:49 UTC
Labels: research, pri/high
