### ISSUE TITLE
Bug: BigQueryGetDataOperator XCOM is unable to deserialise json 

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astronomer-providers#126] opened 2022-03-15 14:30 UTC
- When a date column is present in the Big Query table ,  BigQueryGetDataOperator  is failing to  deserialise json in XCOM

**Comment by phanikumv** [comment] 2022-04-11 11:40
Closing it as this is a duplicate of #127

**Closed by phanikumv** 2022-04-11 11:40 UTC
Labels: bug, pri/low, oss airflow
