### ISSUE TITLE
Livy example DAG failing

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#298] opened 2022-05-02 09:49 UTC
livy_java_task is failing with below error.

`[2022-05-02, 09:43:01 UTC] {livy.py:151} INFO - Submitting job {"file": "/spark-examples.jar", "className": "org.apache.spark.examples.SparkPi", "numExecutors": 1, "conf": {"spark.shuffle.compress": "false"}} to 
[2022-05-02, 09:43:01 UTC] {base.py:68} INFO - Using connection ID 'livy_default' for task execution.
[2022-05-02, 09:43:01 UTC] {http.py:129} INFO - Sending 'POST' to url: http://ec2-18-119-156-7.us-east-2.compute.amazonaws.com:8998/batches
[2022-05-02, 09:45:10 UTC] {http.py:187} WARNING - HTTPConnectionPool(host='ec2-18-119-156-7.us-east-2.compute.amazonaws.com', port=8998): Max retries exceeded with url: /batches (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d1caf9940>: Failed to establish a new connection: [Errno 110] Connection timed out')) Tenacity will retry to execute the operation
[2022-05-02, 09:45:10 UTC] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4d1caf9940>: Failed to establish a new connection: [Errno 110] Connection timed out`

**Comment by pankajkoti** [comment] 2022-05-10 07:03
The issue is no longer observed. Closing this ticket. Can reopen for investigation if we observe it again.

**Closed** 2022-05-12 08:17 UTC
Labels: bug, pri/high
